name: stroll_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  flutter_screenutil: ^5.9.3
  hooks_riverpod: ^2.6.1
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  flutter_hooks: ^0.21.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/Proxima Nova Thin.otf
          weight: 100
        - asset: fonts/Proxima Nova Regular.otf
          weight: 400
        - asset: fonts/Proxima Nova SemiBold.otf
          weight: 600
        - asset: fonts/Proxima Nova Bold.otf
          weight: 700
        - asset: fonts/Proxima Nova ExtraBold.otf
          weight: 800
        - asset: fonts/Proxima Nova Black.otf
          weight: 900